import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {StringStore} from '../src/strings.mjs';
test('deduplicated definitions retain both owned actions and require exact selection when ambiguous',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'kloudy-multiple-'));const executed=[];
 const client={state:{sessionId:'same'},session:async()=>{},ask:async goal=>({sessionId:'same',selection_id:goal,arguments:{text:goal},toolbox:{tools:[{name:'create',inputSchema:{type:'object'}}]}}),call:async(name,args,options)=>{assert.equal(args.text,options.selectionId);executed.push(options.selectionId);return {state:'completed'};}};
 try{const store=new StringStore({file:join(dir,'strings.json'),project:dir,connect:async(s,k,work)=>work(client)});await store.save('two',[{source:'notes',kind:'mcp',goal:'first'},{source:'notes',kind:'mcp',goal:'second'}]);const result=await store.use('two');assert.equal(result.toolbox.tools.length,1);assert.equal(result.selections.length,2);await assert.rejects(()=>store.call('two',result.routes[0].name,{text:'second'}),e=>e.code==='ambiguous_selection');await store.call('two',result.routes[0].name,{text:'second'},{selectionId:'second'});assert.deepEqual(executed,['second']);}finally{await rm(dir,{recursive:true,force:true});}
});
test('saved mixed MCP/SDK/CLI intents reselect, deduplicate and isolate projects; no action calls',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'kloudy-strings-'));let clock=1000,count=0;const calls=[];const options={file:join(dir,'strings.json'),project:join(dir,'project-a'),now:()=>clock,connect:async(source,kind,work)=>{calls.push({source,kind});return work({ask:async()=>({sessionId:source+'-session',selection_id:'fresh-'+(++count),toolbox:{tools:[{name:'read',inputSchema:{type:'object'}}]}})});}};
 try{const store=new StringStore(options);await store.save('mixed',[{source:'notes',kind:'mcp',goal:'read notes'},{source:'notes',kind:'mcp',goal:'get notes'},{source:'sdk',kind:'sdk',goal:'read resource'},{source:'cli',kind:'cli',goal:'inspect resource'}]);const a=await store.use('mixed'),b=await store.use('mixed');assert.equal(a.toolbox.tools.length,3);assert.equal(a.routes.length,4);assert.equal(a.routes[0].name,a.routes[1].name);await assert.rejects(()=>store.call('mixed',b.routes[0].name,{}),e=>e.code==='ambiguous_selection');assert.equal(new Set(a.toolbox.tools.map(t=>t.name)).size,3);assert.notEqual(a.routes[0].selection_id,b.routes[0].selection_id);assert.deepEqual(calls.slice(0,4).map(c=>c.kind),['mcp','mcp','sdk','cli']);assert.equal((await new StringStore({...options,project:join(dir,'other')}).list()).length,0);assert.ok(!(await readFile(options.file,'utf8')).includes('inputSchema'));await assert.rejects(()=>store.save('mixed',[]));await store.keep('mixed');clock+=40*86400000;assert.deepEqual((await store.prune()).removed,[]);await store.remove('mixed');await assert.rejects(()=>store.use('mixed'),e=>e.code==='not_found');}finally{await rm(dir,{recursive:true,force:true});}
});
test('string calls use the exact source route and reject changed sessions before execution',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'kloudy-string-call-'));let session='one',executions=0;const client={state:{sessionId:'one'},session:async()=>{client.state.sessionId=session;},ask:async()=>({sessionId:'one',selection_id:'owned-selection',toolbox:{tools:[{name:'read',inputSchema:{type:'object'}}]}}),call:async(name,args,options)=>{assert.equal(name,'read');assert.equal(options.selectionId,'owned-selection');executions++;return {state:'completed'};}};
 try{const store=new StringStore({file:join(dir,'strings.json'),project:dir,connect:async(source,kind,work)=>{assert.equal(source,'owned');return work(client);}});await store.save('work',[{source:'owned',kind:'sdk',goal:'Read the resource'}]);await assert.rejects(()=>store.call('work','s0_read',{}),e=>e.code==='not_selected');const box=await store.use('work');assert.equal((await store.call('work',box.routes[0].name,{})).state,'completed');session='changed';await assert.rejects(()=>store.call('work',box.routes[0].name,{}),e=>e.code==='stale_selection');assert.equal(executions,1);}finally{await rm(dir,{recursive:true,force:true});}
});
test('expired/missing selections fail without returning a partial toolbox; dormant definitions are pruned',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'kloudy-strings-'));let clock=0;const store=new StringStore({file:join(dir,'strings.json'),project:dir,now:()=>clock,connect:async()=>({toolbox:{tools:[]}})});
 try{await assert.rejects(()=>store.save('x',[{source:'a',kind:'mcp',goal:'read',access_token:'secret'}]),e=>e.code==='invalid_selection');await store.save('x',[{source:'a',kind:'mcp',goal:'read'}]);await assert.rejects(()=>store.use('x'),e=>e.code==='selection_unavailable');clock=31*86400000;assert.deepEqual((await store.prune()).removed,['x']);assert.equal((await store.list()).length,0);}finally{await rm(dir,{recursive:true,force:true});}
});
