import {build} from 'esbuild';
import {readFile,writeFile} from 'node:fs/promises';
const result=await build({entryPoints:['ui/sample.mjs'],bundle:true,write:false,format:'iife',platform:'browser',minify:true,legalComments:'inline',metafile:true});
const packages=new Set();for(const input of Object.keys(result.metafile.inputs)){const matches=[...input.matchAll(/(?:^|\/)node_modules\/((?:@[^/]+\/)?[^/]+)/g)],last=matches.at(-1);if(last)packages.add(input.slice(0,last.index+last[0].length));}
const notices=[];for(const root of [...packages].sort())for(const file of ['LICENSE','LICENSE.md','LICENSE.txt','NOTICE'])try{notices.push(root+'/'+file+'\n'+await readFile(root+'/'+file,'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;}
const html=(await readFile('ui/sample.html','utf8')).replace('/* SAMPLE_CSS */',await readFile('ui/sample.css','utf8')).replace('<!-- SAMPLE_SCRIPT -->',()=>'<script>'+result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')+'</script><script type="text/plain" id="notices">'+notices.join('\n\n').replace(/<\/script/gi,'<\\/script')+'</script>');
await writeFile('src/sample-ui.mjs','// Generated by scripts/build-sample.mjs\nexport const sampleHTML='+JSON.stringify(html)+';\n');
