import {build} from 'esbuild';
import {readFile,writeFile} from 'node:fs/promises';
const result=await build({entryPoints:['ui/connect.mjs'],bundle:true,write:false,format:'iife',platform:'browser',minify:true,legalComments:'inline',metafile:true});
const packages=new Set();
for(const input of Object.keys(result.metafile.inputs)){
 const matches=[...input.matchAll(/(?:^|\/)node_modules\/((?:@[^/]+\/)?[^/]+)/g)];
 const last=matches.at(-1);if(last)packages.add(input.slice(0,last.index+last[0].length));
}
const notices=[];
for(const root of [...packages].sort())for(const filename of ['LICENSE','LICENSE.md','LICENSE.txt','NOTICE']){
 try{notices.push(root+' / '+filename+'\n'+await readFile(root+'/'+filename,'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;}
}
const template=await readFile('ui/connect.html','utf8');
const html=template.replace('<!-- CONNECT_SCRIPT -->',()=>'<script>'+result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')+'</script><script type="text/plain" id="third-party-notices">'+notices.join('\n\n').replace(/<\/script/gi,'<\\/script')+'</script>');
await writeFile('src/connect-ui.mjs','// Generated by scripts/build-connect.mjs. Source: ui/connect.*.\nexport const connectHTML='+JSON.stringify(html)+';\n');
